CREATE DATABASE api_db;

USE api_db;

CREATE TABLE motors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    mark VARCHAR(100) NOT NULL UNIQUE,
    cylinder INT NOT NULL UNIQUE,
    year INT NOT NULL UNIQUE
);
CREATE TABLE parts(
    id INT AUTO_INCREMENT PRIMARY KEY,
    oil VARCHAR(100) NOT NULL UNIQUE,
    transmission VARCHAR(50) NOT NULL UNIQUE,
    battery VARCHAR(50) NOT NULL UNIQUE
);